sudo: required
dist: trusty

addons:
   chrome: stable

language: php

php:
    - 7.0
    - 7.1
    - 7.2

services:
    - memcached

notifications:
  email:
    - barryo@inex.ie

before_install:
    - sudo apt-get update
    - sudo apt-get install npm nodejs-legacy
    - "./data/travis-ci/setup_tests.sh"

after_failure:
    - "./data/travis-ci/after_failure.sh"

