name: CI Tests (ex Dusk)

on: [ push, pull_request ]

jobs:
  ci-ex-dusk:

    runs-on: ubuntu-24.04

    steps:
    - uses: shivammathur/setup-php@v2
      with:
        php-version: '8.4'
      env:
        update: true
    - uses: actions/checkout@v2
    - uses: shogo82148/actions-setup-mysql@v1
      with:
        mysql-version: '8.0'
    - name: Print PHP version
      run: echo ${{ steps.setup-php.outputs.php-version }}
    - run: mysql -u root -h 127.0.0.1 -e 'CREATE DATABASE ixp_ci; CREATE USER IF NOT EXISTS ixp_ci@localhost IDENTIFIED BY "ixp_ci"; GRANT ALL ON ixp_ci.* TO ixp_ci@localhost;'
    - name: Copy .env
      run: php -r "file_exists('.env') || copy('.env.ci', '.env');"
    - name: Install bgpq3
      run: sudo apt-get install bgpq3
    - name: Install Dependencies
      run: composer install -q --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist
    - name: Fix temporary issue between laravel-ide-helper and psalm-laravel
      run: cp -f data/ci/known-good/Alias.php vendor/barryvdh/laravel-ide-helper/src/Alias.php
    - name: Directory Permissions
      run: chmod -R 777 storage bootstrap/cache
    - name: Create Database
      run: |
        cat data/ci/ci_test_db.sql  | mysql --default-character-set=utf8mb4 -h localhost -u root ixp_ci
    - name: Set up php server
      run: |
        php ./artisan serve  &>php-built-in.log &
    - name: Execute tests (Unit and Feature tests) via PHPUnit
      run: vendor/bin/phpunit --testsuite 'Docstore Test Suite,IXP Manager Test Suite'
    - name: Static code analysis
      run: vendor/bin/psalm --use-baseline psalm-baseline.xml

